name: website
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bootstrap
        run: |
          source ${{github.workspace}}/bootstrap.sh
      - name: generate
        run: |
          source ${{github.workspace}}/build.sh
      - name: pages
        uses: actions/configure-pages@v5
      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{github.workspace}}/_build/html
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    needs: build
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: deploy
        uses: actions/deploy-pages@v4
